# Site Settings
lang: en
timezone: Asia/Ho_Chi_Minh

# Jekyll Configuration
title: Alex Tran
tagline: Exploring how we build software, systems, and teams that scale.
description: >-
  Personal blog and portfolio showcasing projects and thoughts on technology, 
  development, AI, and the craft of building meaningful software.

url: "https://ptranalex.github.io"
baseurl: ""

# GitHub configuration (for sidebar icon)
github:
  username: ptranalex

# Twitter/X configuration (optional - uncomment to add Twitter icon)
# twitter:
#   username: yourusername

# Theme Settings
theme: jekyll-theme-chirpy

# Social media
social:
  name: Alex Tran
  email: me@alexsandbox.me
  links:
    - https://github.com/ptranalex
    - https://www.linkedin.com/in/ptranalex/

# Site verification (optional - for search engines)
# google_site_verification:
# bing_site_verification:

# Analytics (optional)
# google_analytics:
#   id:

# Theme mode toggle button will appear when theme_mode is not set
# Remove this line to show the mode toggle button in the sidebar
# theme_mode: auto

# Avatar
avatar: /assets/images/avatar.jpg

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Jekyll Archives (for categories and tags)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Exclude from processing
exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
  - Gemfile
  - Gemfile.lock
  - vendor
